apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pantreasy-ingress
  namespace: pantreasy-dev
spec:
  ingressClassName: nginx
  rules:
    - host: pantreasy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pantreasy
                port:
                  number: 80